## 0.Librerias y Funciones

#### Librerias

In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None 
import os
import sys
import lightgbm as lgb
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestRegressor

pd.options.display.max_rows=100
pd.options.display.max_columns=500

In [2]:
os.getcwd()

'C:\\Users\\KEVIN\\Downloads\\DSRP\\Machine Learning III\\DSRP_MLE3\\notebooks'

## 1. Data Raw: Exploracion

In [3]:
RAW_DATA_DIR = "../data/raw/"
PROCESSED_DATA_DIR = "../data/processed/"

In [4]:
data_raw = pd.read_csv(RAW_DATA_DIR+"PS_20174392719_1491204439457_log.csv")
print(data_raw.shape)

(6362620, 11)

In [5]:
data_raw.head(100)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.00,0.00,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.00,0.00,0,0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.00,0.00,1,0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.00,0.00,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.00,0.00,0,0
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.00,0.00,0,0
6,1,PAYMENT,7107.77,C154988899,183195.00,176087.23,M408069119,0.00,0.00,0,0
7,1,PAYMENT,7861.64,C1912850431,176087.23,168225.59,M633326333,0.00,0.00,0,0
8,1,PAYMENT,4024.36,C1265012928,2671.00,0.00,M1176932104,0.00,0.00,0,0
9,1,DEBIT,5337.77,C712410124,41720.00,36382.23,C195600860,41898.00,40348.79,0,0
10,1,DEBIT,9644.94,C1900366749,4465.00,0.00,C997608398,10845.00,157982.12,0,0
11,1,PAYMENT,3099.97,C249177573,20771.00,17671.03,M2096539129,0.00,0.00,0,0
12,1,PAYMENT,2560.74,C1648232591,5070.00,2509.26,M972865270,0.00,0.00,0,0
13,1,PAYMENT,11633.76,C1716932897,10127.00,0.00,M801569151,0.00,0.00,0,0
14,1,PAYMENT,4098.78,C1026483832,503264.00,499165.22,M1635378213,0.00,0.00,0,0
15,1,CASH_OUT,229133.94,C905080434,15325.00,0.00,C476402209,5083.00,51513.44,0,0
16,1,PAYMENT,1563.82,C761750706,450.00,0.00,M1731217984,0.00,0.00,0,0
17,1,PAYMENT,1157.86,C1237762639,21156.00,19998.14,M1877062907,0.00,0.00,0,0
18,1,PAYMENT,671.64,C2033524545,15123.00,14451.36,M473053293,0.00,0.00,0,0
19,1,TRANSFER,215310.30,C1670993182,705.00,0.00,C1100439041,22425.00,0.00,0,0
20,1,PAYMENT,1373.43,C20804602,13854.00,12480.57,M1344519051,0.00,0.00,0,0
21,1,DEBIT,9302.79,C1566511282,11299.00,1996.21,C1973538135,29832.00,16896.70,0,0
22,1,DEBIT,1065.41,C1959239586,1817.00,751.59,C515132998,10330.00,0.00,0,0
23,1,PAYMENT,3876.41,C504336483,67852.00,63975.59,M1404932042,0.00,0.00,0,0
24,1,TRANSFER,311685.89,C1984094095,10835.00,0.00,C932583850,6267.00,2719172.89,0,0
25,1,PAYMENT,6061.13,C1043358826,443.00,0.00,M1558079303,0.00,0.00,0,0
26,1,PAYMENT,9478.39,C1671590089,116494.00,107015.61,M58488213,0.00,0.00,0,0
27,1,PAYMENT,8009.09,C1053967012,10968.00,2958.91,M295304806,0.00,0.00,0,0
28,1,PAYMENT,8901.99,C1632497828,2958.91,0.00,M33419717,0.00,0.00,0,0
29,1,PAYMENT,9920.52,C764826684,0.00,0.00,M1940055334,0.00,0.00,0,0
30,1,PAYMENT,3448.92,C2103763750,0.00,0.00,M335107734,0.00,0.00,0,0
31,1,PAYMENT,4206.84,C215078753,0.00,0.00,M1757317128,0.00,0.00,0,0
32,1,PAYMENT,5885.56,C840514538,0.00,0.00,M1804441305,0.00,0.00,0,0
33,1,PAYMENT,5307.88,C1768242710,0.00,0.00,M1971783162,0.00,0.00,0,0
34,1,PAYMENT,5031.22,C247113419,0.00,0.00,M151442075,0.00,0.00,0,0
35,1,PAYMENT,24213.67,C1238616099,0.00,0.00,M70695990,0.00,0.00,0,0
36,1,PAYMENT,8603.42,C1608633989,253.00,0.00,M1615617512,0.00,0.00,0,0
37,1,PAYMENT,2791.42,C923341586,300481.00,297689.58,M107994825,0.00,0.00,0,0
38,1,PAYMENT,7413.54,C1470868839,297689.58,290276.03,M1426725223,0.00,0.00,0,0
39,1,PAYMENT,3295.19,C711197015,233633.00,230337.81,M1384454980,0.00,0.00,0,0
40,1,PAYMENT,1684.81,C1481594086,297.00,0.00,M1569435561,0.00,0.00,0,0
41,1,DEBIT,5758.59,C1466917878,32604.00,26845.41,C1297685781,209699.00,16997.22,0,0
42,1,CASH_OUT,110414.71,C768216420,26845.41,0.00,C1509514333,288800.00,2415.16,0,0
43,1,PAYMENT,7823.46,C260084831,998.00,0.00,M267814113,0.00,0.00,0,0
44,1,PAYMENT,5086.48,C598357562,0.00,0.00,M1593224710,0.00,0.00,0,0
45,1,PAYMENT,5281.48,C1440738283,152019.00,146737.52,M1849015357,0.00,0.00,0,0
46,1,PAYMENT,13875.98,C484199463,15818.00,1942.02,M2008106788,0.00,0.00,0,0
47,1,CASH_OUT,56953.90,C1570470538,1942.02,0.00,C824009085,70253.00,64106.18,0,0
48,1,CASH_OUT,5346.89,C512549200,0.00,0.00,C248609774,652637.00,6453430.91,0,0
49,1,PAYMENT,2204.04,C1615801298,586.00,0.00,M490391704,0.00,0.00,0,0
50,1,PAYMENT,2641.47,C460570271,23053.00,20411.53,M1653361344,0.00,0.00,0,0
51,1,CASH_OUT,23261.30,C2072313080,20411.53,0.00,C2001112025,25742.00,0.00,0,0
52,1,PAYMENT,2330.64,C816944408,203543.00,201212.36,M909132503,0.00,0.00,0,0
53,1,PAYMENT,1614.64,C912966811,41276.00,39661.36,M1792384402,0.00,0.00,0,0
54,1,PAYMENT,9164.71,C1458621573,47235.77,38071.06,M1658980982,0.00,0.00,0,0
55,1,PAYMENT,2970.97,C46941357,38071.06,35100.09,M1152606315,0.00,0.00,0,0
56,1,PAYMENT,38.66,C343345308,16174.00,16135.34,M1714688478,0.00,0.00,0,0
57,1,PAYMENT,2252.44,C104716441,1627.00,0.00,M1506951181,0.00,0.00,0,0
58,1,TRANSFER,62610.80,C1976401987,79114.00,16503.20,C1937962514,517.00,8383.29,0,0
59,1,DEBIT,5529.13,C867288517,8547.00,3017.87,C242131142,10206.00,0.00,0,0
60,1,CASH_OUT,82940.31,C1528834618,3017.87,0.00,C476800120,132372.00,49864.36,0,0
61,1,DEBIT,4510.22,C280615803,10256.00,5745.78,C1254526270,10697.00,0.00,0,0
62,1,DEBIT,8727.74,C166694583,882770.00,874042.26,C1129670968,12636.00,0.00,0,0
63,1,PAYMENT,2599.46,C885910946,874042.26,871442.79,M1860591867,0.00,0.00,0,0
64,1,DEBIT,4874.49,C811207775,153.00,0.00,C1971489295,253104.00,0.00,0,0
65,1,PAYMENT,6440.78,C1161148117,2192.00,0.00,M516875052,0.00,0.00,0,0
66,1,PAYMENT,4910.14,C1131592118,41551.00,36640.86,M589987187,0.00,0.00,0,0
67,1,PAYMENT,6444.64,C1262609629,12019.00,5574.36,M587180314,0.00,0.00,0,0
68,1,DEBIT,5149.66,C1955990522,4782.00,0.00,C1330106945,52752.00,24044.18,0,0
69,1,PAYMENT,7292.16,C69673470,216827.00,209534.84,M1082411691,0.00,0.00,0,0
70,1,CASH_OUT,47458.86,C527211736,209534.84,162075.98,C2096057945,52120.00,0.00,0,0
71,1,CASH_OUT,136872.92,C1533123860,162075.98,25203.05,C766572210,217806.00,0.00,0,0
72,1,CASH_OUT,94253.33,C1718906711,25203.05,0.00,C977993101,99773.00,965870.05,0,0
73,1,PAYMENT,2998.04,C71802912,12030.00,9031.96,M2134271532,0.00,0.00,0,0
74,1,PAYMENT,3454.08,C686349795,9031.96,5577.88,M1831010686,0.00,0.00,0,0
75,1,PAYMENT,4316.20,C1423768154,10999.00,6682.80,M404222443,0.00,0.00,0,0
76,1,PAYMENT,2131.84,C1987977423,224.00,0.00,M61073295,0.00,0.00,0,0
77,1,PAYMENT,12986.61,C807322507,23350.00,10363.39,M396485834,0.00,0.00,0,0
78,1,TRANSFER,42712.39,C283039401,10363.39,0.00,C1330106945,57901.66,24044.18,0,0
79,1,TRANSFER,77957.68,C207471778,0.00,0.00,C1761291320,94900.00,22233.65,0,0
80,1,TRANSFER,17231.46,C1243171897,0.00,0.00,C783286238,24672.00,0.00,0,0
81,1,TRANSFER,78766.03,C1376151044,0.00,0.00,C1749186397,103772.00,277515.05,0,0
82,1,TRANSFER,224606.64,C873175411,0.00,0.00,C766572210,354678.92,0.00,0,0
83,1,TRANSFER,125872.53,C1443967876,0.00,0.00,C392292416,348512.00,3420103.09,0,0
84,1,TRANSFER,379856.23,C1449772539,0.00,0.00,C1590550415,900180.00,19169204.93,0,0
85,1,TRANSFER,1505626.01,C926859124,0.00,0.00,C665576141,29031.00,5515763.34,0,0
86,1,TRANSFER,554026.99,C1603696865,0.00,0.00,C766572210,579285.56,0.00,0,0
87,1,TRANSFER,147543.10,C12905860,0.00,0.00,C1359044626,223220.00,16518.36,0,0
88,1,TRANSFER,761507.39,C412788346,0.00,0.00,C1590550415,1280036.23,19169204.93,0,0
89,1,TRANSFER,1429051.47,C1520267010,0.00,0.00,C1590550415,2041543.62,19169204.93,0,0
90,1,TRANSFER,358831.92,C908084672,0.00,0.00,C392292416,474384.53,3420103.09,0,0
91,1,TRANSFER,367768.40,C288306765,0.00,0.00,C1359044626,370763.10,16518.36,0,0
92,1,TRANSFER,209711.11,C1556867940,0.00,0.00,C1509514333,399214.71,2415.16,0,0
93,1,TRANSFER,583848.46,C1839168128,0.00,0.00,C1286084959,667778.00,2107778.11,0,0
94,1,TRANSFER,1724887.05,C1495608502,0.00,0.00,C1590550415,3470595.10,19169204.93,0,0
95,1,TRANSFER,710544.77,C835773569,0.00,0.00,C1359044626,738531.50,16518.36,0,0
96,1,TRANSFER,581294.26,C843299092,0.00,0.00,C1590550415,5195482.15,19169204.93,0,0
97,1,TRANSFER,11996.58,C605982374,0.00,0.00,C1225616405,40255.00,0.00,0,0
98,1,PAYMENT,2875.10,C1412322831,15443.00,12567.90,M1651262695,0.00,0.00,0,0
99,1,PAYMENT,8586.98,C1305004711,3763.00,0.00,M494077446,0.00,0.00,0,0

#### Valores

In [6]:
print("isFraud (Target):", data_raw['isFraud'].unique())
print("isFlaggedFraud:", data_raw['isFlaggedFraud'].unique())
print("type:", data_raw['type'].unique())

isFraud (Target): [0 1]
isFlaggedFraud: [0 1]
type: ['PAYMENT' 'TRANSFER' 'CASH_OUT' 'DEBIT' 'CASH_IN']

#### Entidades transaccion

In [7]:
data_raw['entTrxType'] = data_raw['nameOrig'].str[0] + data_raw['nameDest'].str[0]
data_raw['entTrxType'].unique()

array(['CM', 'CC'], dtype=object)

In [8]:
data_raw.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,entTrxType
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0,CM
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0,CM
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0,CC
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0,CC
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0,CM

In [9]:
data_raw[data_raw['type'] == 'CASH_IN'].head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,entTrxType
389,1,CASH_IN,143236.26,C1862994526,0.00,143236.26,C1688019098,608932.17,97263.78,0,0,CC
390,1,CASH_IN,228451.89,C1614133563,143236.26,371688.15,C2083562754,719678.38,1186556.81,0,0,CC
391,1,CASH_IN,35902.49,C839771540,371688.15,407590.65,C2001112025,49003.30,0.00,0,0,CC
392,1,CASH_IN,232953.64,C1037163664,407590.65,640544.28,C33524623,1172672.27,1517262.16,0,0,CC
393,1,CASH_IN,65912.95,C180316302,640544.28,706457.23,C1330106945,104198.26,24044.18,0,0,CC

#### Monto transaccion

In [10]:
data_raw['origTrxAmount'] = data_raw['newbalanceOrig'] - data_raw['oldbalanceOrg']
data_raw['destTrxAmount'] = np.where(data_raw['entTrxType'] == "CM", np.nan, data_raw['newbalanceDest'] - data_raw['oldbalanceDest'])
#se considera NaN para los casos "CM" para diferenciar los valores "CC" con valor 0.

In [11]:
data_raw.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,entTrxType,origTrxAmount,destTrxAmount
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0,CM,-9839.64,NaN
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0,CM,-1864.28,NaN
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0,CC,-181.00,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0,CC,-181.00,-21182.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0,CM,-11668.14,NaN

In [12]:
data_raw[data_raw['type'] == 'CASH_IN'].head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,entTrxType,origTrxAmount,destTrxAmount
389,1,CASH_IN,143236.26,C1862994526,0.00,143236.26,C1688019098,608932.17,97263.78,0,0,CC,143236.26,-511668.39
390,1,CASH_IN,228451.89,C1614133563,143236.26,371688.15,C2083562754,719678.38,1186556.81,0,0,CC,228451.89,466878.43
391,1,CASH_IN,35902.49,C839771540,371688.15,407590.65,C2001112025,49003.30,0.00,0,0,CC,35902.50,-49003.30
392,1,CASH_IN,232953.64,C1037163664,407590.65,640544.28,C33524623,1172672.27,1517262.16,0,0,CC,232953.63,344589.89
393,1,CASH_IN,65912.95,C180316302,640544.28,706457.23,C1330106945,104198.26,24044.18,0,0,CC,65912.95,-80154.08

#### Flags de fraude

In [13]:
data_raw[data_raw['isFlaggedFraud'] == 1].head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,entTrxType,origTrxAmount,destTrxAmount
2736446,212,TRANSFER,4953893.08,C728984460,4953893.08,4953893.08,C639921569,0.0,0.0,1,1,CC,0.0,0.0
3247297,250,TRANSFER,1343002.08,C1100582606,1343002.08,1343002.08,C1147517658,0.0,0.0,1,1,CC,0.0,0.0
3760288,279,TRANSFER,536624.41,C1035541766,536624.41,536624.41,C1100697970,0.0,0.0,1,1,CC,0.0,0.0
5563713,387,TRANSFER,4892193.09,C908544136,4892193.09,4892193.09,C891140444,0.0,0.0,1,1,CC,0.0,0.0
5996407,425,TRANSFER,10000000.00,C689608084,19585040.37,19585040.37,C1392803603,0.0,0.0,1,1,CC,0.0,0.0

In [14]:
data_raw[(data_raw['isFlaggedFraud'] == 1)&(data_raw['isFraud'] == 0)] #todos los registros isFlaggedFraud=1 estan marcados como isFraud=1

Empty DataFrame
Columns: [step, type, amount, nameOrig, oldbalanceOrg, newbalanceOrig, nameDest, oldbalanceDest, newbalanceDest, isFraud, isFlaggedFraud, entTrxType, origTrxAmount, destTrxAmount]
Index: []

#### Base

In [15]:
data_raw['base'] = np.where(data_raw['step'] <= 400, 0, 2) # 0=Desarrollo, 2=Produccion

In [16]:
data_raw.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,entTrxType,origTrxAmount,destTrxAmount,base
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0,CM,-9839.64,NaN,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0,CM,-1864.28,NaN,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0,CC,-181.00,0.0,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0,CC,-181.00,-21182.0,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0,CM,-11668.14,NaN,0

In [6]:
df_train = data_raw[data_raw['base']==0]
df_train = df_train.drop(columns={'base'})
df_train.to_csv(RAW_DATA_DIR+"train.csv", index=False)
del df_train

In [ ]:
df_prod = data_raw[data_raw['base']==2]
df_prod = df_prod.drop(columns={'base'})
df_prod.to_csv(RAW_DATA_DIR+"prod.csv", index=False)
del df_prod

#### Target

In [32]:
data_raw['step'].value_counts().sort_index(ascending=True)

step
1      2708
2      1014
3       552
4       565
5       665
       ...
739      10
740       6
741      22
742      14
743       8
Name: count, Length: 743, dtype: int64

In [35]:
data_raw.groupby('base').agg({'isFraud':'mean'})

       isFraud
base
0     0.000774
2     0.006491

## 2. Data Processed: Export

In [17]:
data_raw = data_raw[data_raw['isFlaggedFraud'] == 0] # Solo se consideran los 0, puesto que esta marca es una decision de imputacion

In [18]:
cols_export = ['base','type','amount','entTrxType','oldbalanceOrg','origTrxAmount','oldbalanceDest','destTrxAmount','isFraud']
data_raw[cols_export].to_parquet(PROCESSED_DATA_DIR+"processed.parquet", engine='pyarrow', compression='GZIP')